const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkpWcnVOdmtUd2MwM0Y2UCs3b1pzbktmcitDL20wR2ZWZEM5UnZob1JsWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZytyejdzMk5jQjdSNDI5VzJwZ0M5RHVmQzRiVitWYXVQVTQwbkpHVDNSRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIwUGNGWm5QYXFOOE1lQUtFVTU3MVlZRGJqSW1uTk16UmZLTmVRRU9yQTFvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFUUQ2STNPQ3lvY0VLMGJKa3Y3UzdkMHZ4QVkxdUtRUGVCdEtyckQrZUE0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktJam1CdTBuNFVRRE5SY0hWZ0Y1czkvc0RmVVhrdmNpZ2FEaUVsQXNjVXM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJVU1VOd05tWkJzUTRmSHJ2NHpSUDA5UTVsaGEydkN0MFhqZGlUQVhBaXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSUVWY0FCbjB0NzdtZ0RackZ2UVFQZ1dVTzlmY1ViUU45SzlyZ2ZWMEgxZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiOGVuVjJZL2c3bkp6MWc4VzFRZmwxZ1JuZ3k5aGNvZHZnaXAreFJyUXJtUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNQb1VRUnRNOHVadm1aT2xpTktCU1NmdGJPdnJZN1hsZHZmTjJOZWdiSktFYTBSYVc3MkNVYmR5VzBZajhqY2VhSWtCU1NmdUU4ZjlERDNLQ1hGZWpBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NjAsImFkdlNlY3JldEtleSI6ImJPcWx4OW4vNzNvNnpKcGhzWXFvY2N3MXhyd2lCUjEreUx3RTZBU1dXM1U9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTAzODkwOTYxOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5NjVBRjkyQjkzNzQ4NUY1MEFFQkEwNzk5QzlFN0VGQyJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1ODI5NTg2fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyMzQ5MDM4OTA5NjE4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjA5Qzk5QUNENzgyN0YzMDkxRTFDMTJBRkFENjc3QTNDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU4Mjk1ODZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzNDkwMzg5MDk2MThAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiNzBGODVFNUI1QkZBNTkxRjlBRDU0RTlBMzE2RkZGQjQifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTgyOTU4OH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjM0OTAzODkwOTYxOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI5ODMwODkxRDBFNjVGQjFDQjhGMUYzRkVFRTM5OUU5RCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1ODI5NTg5fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiI3VGpOTDZYSlRhcWRsUFRvdUZPWTVBIiwicGhvbmVJZCI6ImJiM2ZjYWUyLTBjNzItNGU0NC1iZDM2LTQ0YTJhYjBjODc3ZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI1eGhCbzRCSVAzR2lHNTBFS01qbEhEaExKajg9In0sInJlZ2lzdGVyZWQiOmZhbHNlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVjZHdHMnB1Z2Y2UjNlajNnN0ZHMldFUitoST0ifSwicmVnaXN0cmF0aW9uIjp7fSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0xQZXZMc0JFTUxRMnJzR0dBSWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6Ikk3N0NjTk9BU0dnUWxOdk5DU2QydFZWSHE5UzVoTnNmdzVIeEFzSXBTR0k9IiwiYWNjb3VudFNpZ25hdHVyZSI6InVGbGR6bEtHcjByU0ZRVHEzZkFEQnE2ZEJRSDViMFFrTmFrdHQ0VkxKL1hsTDJIMTdzY2M5TmhpNk9RQUQ1UGlNQ0hvYStYbU1vZkpjTk11dnNBb0NRPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJISUxqOGtQYUl0TGt2R2JKMWUrOFJtSTNjb1lraEx5YXIzTWt2bWk4Q2dNSDZmNVF0S0tGV1B1by9XSEVLQ3VCRnFPeWVuV0Mxc1hoRTY3MCs1bG1qQT09In0sIm1lIjp7ImlkIjoiMjM0OTAzODkwOTYxODoyQHMud2hhdHNhcHAubmV0IiwibmFtZSI6Inhlcm9mZng3MSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzQ5MDM4OTA5NjE4OjJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCU08rd25EVGdFaG9FSlRielFrbmRyVlZSNnZVdVlUYkg4T1I4UUxDS1VoaSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTgyOTU4MywibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFGYVYifQ==
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "2349038909618",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
